### ISSUE TITLE
【报错】无法保存jkdrcom.json

### ISSUE THREAD

**Issue by Sohnia** [Winterreisender/JKDrcom#3]
原因：没有C:\Users\Administrator\.drcom这个文件夹

结果方案：判断C:\Users\Administrator\.drcom是否存在，不存在就新建。然后再保存jkdrcom.json

**Comment by Sohnia** [comment]
/[jkdrcom](https://github.com/Winterreisender/JKDrcom/tree/master/src/main/java/io/github/winterreisender/jkdrcom)/[gui](https://github.com/Winterreisender/JKDrcom/tree/master/src/main/java/io/github/winterreisender/jkdrcom/gui)/AppConfig.kt

问题出在上述类中的saveToFile方法。

**Comment by Winterreisender** [comment]
感谢反馈。已查明原因并着手修复。
实在没想到真的会有别人用。

**Comment by Winterreisender** [comment]
已在 bdb4b4b 提交中尝试修复。

**Comment by Sohnia** [comment]
> 已在 [bdb4b4b](https://github.com/Winterreisender/JKDrcom/commit/bdb4b4b17d13433cb1aa7ab8221da4f270665d2b) 提交中尝试修复。

我不太会kt，要是会kt可以fork你的项目进行开发。

**Comment by Winterreisender** [comment]
断线重连功能是有的，在`菜单栏->功能->设置重试次数`那里，只不过默认重试次数是1。

建议4很好，已经决定着手开发。

建议1请详细描述一下，虽然读过协议分析但是不太明白是`ip连接之后的地址`指的是什么。

JKDrcom的联网功能是和drcom-java完全相同的，只是重写了GUI，并没有代替官方客户端的目的和能力，JKDrcom还在早期开发阶段，不像Drcom那样稳定完善。
